### PR TITLE
Solve problem: Always clear the cache after db-import

### PR DESCRIPTION
**Pull request by Yuvania**
Since DrushDeployCommand is a command that is run after a DB import, to solve the issue reported by Dave, I added the commands to clear the cache and import the configuration before updating the database and in this way, we avoid random errors.

### CODE REVIEW

**Comment by Yuvania** [comment]
This is the issue https://github.com/fourkitchens/fire/issues/22

**Comment by rigoucr** [comment]
@Yuvania look at this :
https://github.com/fourkitchens/fire/issues/22#issuecomment-2264142635

**Comment by Yuvania** [comment]
According to the comment "_**think this change goes more into the the command src/Robo/Plugin/Commands/DrushDeployCommand.php and add just a drush cr at the very beggining of the command exec, thx**_" already add the cr to the beginning of the command

**Review by rigoucr — APPROVED** [review]
Thx @Yuvania , approved

**Pull request merged**
